version: "3"

services:
  test-database-1:
    image: library/postgres:16
    container_name: testdb-1
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'postgres'
    ports:
      - "5435:5432"
